FROM python:3.10-slim

WORKDIR /app

COPY requirements/server.requirements.txt /app/
RUN pip install --no-cache-dir -r server.requirements.txt
COPY setup.cfg setup.py pyproject.toml /app/
COPY src /app/src
RUN pip install --no-cache-dir --no-deps .

COPY client_app /app/client_app
COPY model /app/model

WORKDIR /app/client_app


CMD [ "uvicorn", "app:app", "--host", "0.0.0.0" ]