FROM python:3.10-slim

WORKDIR /app

# This image must have prefect in it
COPY requirements/data-science-deploy.requirements.txt /app/
RUN pip install --no-cache-dir -r data-science-deploy.requirements.txt
COPY setup.cfg setup.py pyproject.toml /app/
COPY src /app/src
RUN pip install --no-cache-dir --no-deps .