FROM python:3.10-slim

WORKDIR /app

COPY requirements/server.requirements.txt /app/
RUN pip install --no-cache-dir -r server.requirements.txt
COPY setup.cfg setup.py pyproject.toml /app/
COPY src /app/src
RUN pip install --no-cache-dir --no-deps .

COPY weather-station /app/weather-station

WORKDIR /app/weather-station
# VOLUME [ "/models" ]
RUN mkdir /scratch



EXPOSE 6000
ENV UVICORN_PORT=6000
CMD [ "python", "weather-station.py"]