FROM python:3.10-slim

WORKDIR /app

COPY requirements/server.requirements.txt /app/
RUN pip install --no-cache-dir -r server.requirements.txt
COPY setup.cfg setup.py pyproject.toml /app/
COPY src /app/src
RUN pip install --no-cache-dir --no-deps .

COPY FastAPI_server /app/FastAPI_server
COPY models /app/models

WORKDIR /app/FastAPI_server
RUN mkdir /scratch

CMD [ "uvicorn", "app:app", "--host", "0.0.0.0" ]