FROM python:3.10-slim

WORKDIR /app

COPY requirements/server.requirements.txt /app/
RUN pip install --no-cache-dir -r server.requirements.txt
COPY setup.cfg setup.py pyproject.toml /app/
COPY src /app/src
COPY data /app/data
RUN pip install --no-cache-dir --no-deps .

COPY client_app /app/client_app

WORKDIR /app/client_app
# VOLUME [ "/models" ]
RUN mkdir /scratch



EXPOSE 6000
ENV UVICORN_PORT=6000
CMD [ "python", "data_server.py"]