on:
  push:
    branches:
      - main
      - dev
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PROJECT_ID: ${{ secrets.GKE_PROJECT }}
  GAR_LOCATION: northamerica-northeast1
  GKE_CLUSTER: ${{ vars.GKE_CLUSTER }}
  GKE_LOCATION: ${{ vars.GKE_LOCATION }}

jobs:
  ci:
    name: Check lint, check format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Set up style and lint generate-requirements
        run: |
          pip install -r requirements/style.requirements.txt

      - name: Lint
        run: |
          ruff check weather-station FastAPI_server src/weather 
      - name: Format check
        run: |
          black --check weather-station FastAPI_server src/weather